# Generated by Django 5.2.7 on 2025-10-19 21:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('setor', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('segmento', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('tipo_opcao', models.CharField(choices=[('C', 'Call'), ('P', 'Put')], default='C', max_length=1)),
                ('modelo', models.CharField(choices=[('AME', 'Americana'), ('EUR', 'Européia')], max_length=3)),
                ('strike', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
            ],
            options={
                'db_table': 'opcoes',
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda')], max_length=6)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=20)),
                ('preco', models.DecimalField(decimal_places=6, max_digits=20)),
                ('corretagem', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('emolumentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('preco_medio', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
