# Generated by Django 5.2.7 on 2025-11-29 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='posicao',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='posicao',
            unique_together={('content_type', 'object_id', 'usuario')},
        ),
    ]
