# Generated by Django 5.2.7 on 2025-10-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posicao',
            options={'verbose_name': 'Posicao', 'verbose_name_plural': 'Posicoes'},
        ),
        migrations.AlterModelTable(
            name='posicao',
            table='posicao',
        ),
    ]
