# Generated by Django 5.2.7 on 2025-11-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0002_alter_operacao_quantidade_alter_posicao_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicao',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
