# Generated by Django 5.2.7 on 2025-12-24 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0004_trade_operacao_trade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estrategia',
                'verbose_name_plural': 'Estrategias',
                'db_table': 'estrategia',
            },
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='trade',
        ),
        migrations.AlterField(
            model_name='operacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posicao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EstrategiaExecutada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_encerramento', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carteira.estrategia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'execucao_estrategia',
                'verbose_name_plural': 'estrategias_executadas',
                'db_table': 'execucao_estrategia',
            },
        ),
        migrations.AddField(
            model_name='operacao',
            name='estrategia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='operacoes', to='carteira.estrategiaexecutada'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
