# Generated by Django 5.2.7 on 2025-12-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0005_estrategia_remove_operacao_trade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacao',
            old_name='estrategia',
            new_name='estrategia_executada',
        ),
    ]
